{
  "trinfinity": {
    "panel_title": "Trinfinity",
    "section_style": "Message Style",
    "section_theme": "Colour Theme",
    "section_font": "Font Pair",
    "section_style_settings": "Style Settings",
    "section_background": "Background",
    "section_button": "Button Position",
    "section_about": "About",
    "font_load_btn": "Load Fonts",
    "font_display_placeholder": "Display font (e.g. Playfair Display)",
    "font_body_placeholder": "Body font (e.g. Lora)",
    "style_gossamer": "Gossamer",
    "style_fade": "Fade",
    "style_pulse": "Pulse",
    "style_ebb": "Ebb",
    "style_flow": "Flow",
    "style_void": "Void",
    "style_loom": "Loom",
    "theme_ultraviolet": "Ultraviolet",
    "theme_viscera": "Viscera",
    "theme_undertow": "Undertow",
    "theme_opulence": "Opulence",
    "theme_ashen": "Ashen",
    "theme_revenant": "Revenant",
    "theme_ember": "Ember",
    "theme_venom": "Venom",
    "theme_requiem": "Requiem",
    "theme_lacuna": "Lacuna",
    "theme_blossom": "Blossom",
    "theme_dusk": "Dusk",
    "slider_blur": "Blur",
    "slider_opacity": "Opacity",
    "slider_feather": "Avatar Feather",
    "slider_fade_start": "Fade Start",
    "slider_fade_reach": "Fade Reach",
    "slider_fade_floor": "Floor Opacity",
    "slider_pulse_speed": "Beat Speed",
    "slider_pulse_intensity": "Intensity",
    "slider_pulse_radius": "Glow Radius",
    "slider_pulse_red": "Red",
    "slider_pulse_green": "Green",
    "slider_pulse_blue": "Blue",
    "slider_ebb_opacity": "Portrait Opacity",
    "slider_ebb_desat": "Desaturate",
    "slider_flow_scale": "Portrait Scale",
    "slider_flow_vibrancy": "Colour Vibrancy",
    "slider_void_lh": "Line Height",
    "slider_void_ls": "Name Spacing",
    "slider_loom_radius": "Corner Softness",
    "slider_loom_vignette": "Vignette",
    "slider_loom_spread": "Vignette Spread",
    "slider_portrait_w": "Portrait Width",
    "slider_portrait_h": "Portrait Height",
    "about_version": "Version",
    "about_author": "by trinity (trinachronism)",
    "about_github": "github.com/trinibots/trinfinity"
  }
}
